version: "3.8"
services:
  wpm:
    container_name: wpm-server
    image: wpm
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - my-volume:/wpm-root/wpm
volumes:
  my-volume: